### ISSUE TITLE
Labojumi

### ISSUE THREAD

**Issue by seleckis** [webrf2016/TO-DO#1]
1. „What needs to be done?“ ir `placeholder`.
2. Klase `cf` jums tur gandrīz nekur nav vajadzīgs.
3. Vertikāli pozicionēt labāk nevis `top: 50%; transform: translateY(-50%);`, bet `top: 0; bottom: 0; margin: auto`, jo `transform` ir ieteicams izmantot tikai tad, kad nav noteikts augstums. `transform` procentos var drusku aizmiglot apmales, tāpēc to ir jālieto ļoti kārtīgi.
4. Visus `<div class="section-list-item cf">` ir jāapvieno vienā konteinerī, piemēram `section-list`.
5. `sectioin-header` ir jābūt `section-header`.
6. Nesaprotu priekš kam `.section-footer` ir `text-align: center;`? Tas neko nedod.
7. `float: left;` ieslēdz `display: block;` automātiski. Varat nerakstīt.
8. `.section-footer-nav { margin-left: 80px; }` neder. ja vēlāk dizaineris prasīs nedaudz palielināt platumu, tad nāksies labot arī šo `margin`. Ir jāizvieto centrā.

**Comment by webrf2016** [comment]
Cerams, būs ok
